version: "3.7"
services:
  postgres:
    container_name: nest-start_postgres
    image: postgres:13.3
    env_file:
      - .dev.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "./postgres"
    volumes:
      - ./postgres:/data/db
    ports:
      - 5432:5432
    restart: always